export const en = {
	Musinex: 'Musinex',
	'Top Songs': 'Top Songs',
	'Top Artists': 'Top Artists',
	'Top Albums': 'Top Albums',
	'Top Playlists': 'Top Playlists',
	'See More': 'See more',
	'Type anything': 'Type anything...',
	by: 'by ',
	Songs: 'Songs',
	Artists: 'Artists',
	Albums: 'Albums',
	Playlists: 'Playlists',
	'Language Settings': 'Language Settings',
	songs: ' songs',
	fans: ' fans',
	albums: ' albums',
	'and other': ' and other',
	'No results': 'No results found',
	Error: 'Error'
}
