export const ru = {
	Musinex: 'Мусинекс',
	'Top Songs': 'Топ песен',
	'Top Artists': 'Топ исполнителей',
	'Top Albums': 'Топ альбомов',
	'Top Playlists': 'Топ плейлистов',
	'See More': 'Смотреть больше',
	'Type anything': 'Введите что-нибудь...',
	by: 'от ',
	Songs: 'Песни',
	Artists: 'Исполнители',
	Albums: 'Альбомы',
	Playlists: 'Плейлисты',
	'Language Settings': 'Настройки языка',
	songs: ' песен',
	fans: ' фанатов',
	albums: ' альбомов',
	'and other': ' и другие',
	'No results': 'Ничего не найдено',
	Error: 'Ошибка'
}
