export const ua = {
	Musinex: 'Мусинекс',
	'Top Songs': 'Топ пісень',
	'Top Artists': 'Топ виконавців',
	'See More': 'Дивитися більше',
	'Top Albums': 'Топ альбомів',
	'Top Playlists': 'Топ плейлистів',
	'Type anything': 'Введіть що-небудь...',
	by: 'від ',
	Songs: 'Пісні',
	Artists: 'Виконавці',
	Albums: 'Альбоми',
	Playlists: 'Плейлисти',
	'Language Settings': 'Налаштування мови',
	songs: ' пісень',
	fans: ' фанів',
	albums: ' альбомів',
	'and other': ' і інші',
	'No results': 'Нічого не знайдено',
	Error: 'Помилка',
	ServerError: 'Помилка сервера',
}
