export const ua = {
	Musinex: 'Мусинекс',
	'Top Songs': 'Топ пісень',
	'Top Artists': 'Топ виконавців',
	'See More': 'Дивитися більше',
	'Top Albums': 'Топ альбомів',
	'Top Playlists': 'Топ плейлистів',
	'Type anything': 'Введіть що-небудь...',
	by: 'від ',
	Songs: 'Пісні',
	Artists: 'Виконавці',
	Albums: 'Альбоми',
	Playlists: 'Плейлисти',
	'Language Settings': 'Налаштування мови',
	songs: ' пісень',
	fans: ' фанів',
	albums: ' альбомів',
	'and other': ' і інші',
	'No results': 'Нічого не знайдено',
	Error: 'Помилка',
	ServerError: 'Помилка сервера',
	More: 'Більше',
	Email: 'Емейл',
	Password: 'Пароль',
	Login: 'Увійти',
	Register: 'Зареєструватися',
	"Password is required": "Пароль обов'язковий",
	"Password must have at least 8 characters": "Пароль повинен містити не менше 8 символів",
	"Entered value does not match email format":	"Введене значення не відповідає формату електронної пошти",
	"Email is required": "Електронна пошта обов'язкова",
	"Dont have an account?": "Немає аккаунта?",
	"Already have an account?": "Вже є аккаунт?",
}
